### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by Shrvvmz** [MejriY/MS2DECIDE#1]
Hi! 

I have tried to use MS2Decide on my own data (btw congratulations on the preprint - exciting idea!), but encountered an issue I wasn´t able to fix (unfortunately, I am not an expert in coding ...). Perhaps you can help me:

C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gnps.ucsd.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\site-packages\ms2decide\K_estimation.py", line 81, in K_estimation
    gnps_res = closest_gnps_by_id(task_id, mgf_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\site-packages\ms2decide\ClosestGNPS.py", line 389, in closest_gnps_by_id
    df_anno = _gnps_annotations_download_results(job_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\site-packages\ms2decide\ClosestGNPS.py", line 261, in _gnps_annotations_download_results
    with urllib.request.urlopen(gnps_download_link.format(task_id)) as url:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\c7401401\AppData\Local\anaconda3\envs\ms2decide_env\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

-> I tried it with both, the test data and also my own - with the FBMN workflow on GNPS being successful. But the workflow always returns this error message. 

Thank you very much in advance for your help!

Best regards from Innsbruck,
Fabian

**Comment by BeniddirLab** [comment]
Dear Fabian
Thank you for your email. Which OS are you using on your computer ? Which library search have you used strict or iterative ?

**Comment by Shrvvmz** [comment]
Thank you for your response. I am using Windows 11 and I have tried both options for the library search strict and iterative - both yield the same error message.
Best regards, Fabian

**Comment by BeniddirLab** [comment]
Dear Fabian. Thank you for your answer.
Could you please send me your files (mgf, csv, sirius identifications.tsv) on mehdi.beniddir@universite-paris-saclay.fr
Best,
Mehdi
